// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBerAmPafM3WcAH_lTtM3af7u5xDWSjvEI',
    appId: '1:334588390943:web:4404c6edf638bae7f6ef2a',
    messagingSenderId: '334588390943',
    projectId: 'eating-now',
    authDomain: 'eating-now.firebaseapp.com',
    databaseURL: 'https://eating-now-default-rtdb.firebaseio.com',
    storageBucket: 'eating-now.appspot.com',
    measurementId: 'G-0TQ4V1JGW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mdM-RLljEn-8Y0N7YIIes_1gUXus5DU',
    appId: '1:334588390943:android:c6f1eab6703294a8f6ef2a',
    messagingSenderId: '334588390943',
    projectId: 'eating-now',
    databaseURL: 'https://eating-now-default-rtdb.firebaseio.com',
    storageBucket: 'eating-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARV-6pbXRpimC4_84CnGBEtVW6JqVxKm8',
    appId: '1:334588390943:ios:3d91dd901ce774a3f6ef2a',
    messagingSenderId: '334588390943',
    projectId: 'eating-now',
    databaseURL: 'https://eating-now-default-rtdb.firebaseio.com',
    storageBucket: 'eating-now.appspot.com',
    androidClientId: '334588390943-a6204t3apm4qqmibl0sr09o8apf97us7.apps.googleusercontent.com',
    iosClientId: '334588390943-m005kolqnlbqbjg2jurd6vu9lm8orka2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARV-6pbXRpimC4_84CnGBEtVW6JqVxKm8',
    appId: '1:334588390943:ios:d2ed229e2e1d6792f6ef2a',
    messagingSenderId: '334588390943',
    projectId: 'eating-now',
    databaseURL: 'https://eating-now-default-rtdb.firebaseio.com',
    storageBucket: 'eating-now.appspot.com',
    androidClientId: '334588390943-a6204t3apm4qqmibl0sr09o8apf97us7.apps.googleusercontent.com',
    iosClientId: '334588390943-3oj062imrm28h2dnom03ae7m5m3o1iie.apps.googleusercontent.com',
    iosBundleId: 'com.example.fam.RunnerTests',
  );
}
