// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasBL27GvwUnuTuu1o7TGKhR01P0Fgta0',
    appId: '1:914139427259:web:01a8f940361094c217149e',
    messagingSenderId: '914139427259',
    projectId: 'my-project-2024-7d367',
    authDomain: 'my-project-2024-7d367.firebaseapp.com',
    storageBucket: 'my-project-2024-7d367.appspot.com',
    measurementId: 'G-NTLCBFGHTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT411X8o88JbpkZNQP1bFsCpjJxaj5vJA',
    appId: '1:914139427259:android:15cffb07cc4c42b317149e',
    messagingSenderId: '914139427259',
    projectId: 'my-project-2024-7d367',
    storageBucket: 'my-project-2024-7d367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICHC7DGkKOgaM__DVF_Jte3Hgvxgf4Pw',
    appId: '1:914139427259:ios:f1f2b2816240040417149e',
    messagingSenderId: '914139427259',
    projectId: 'my-project-2024-7d367',
    storageBucket: 'my-project-2024-7d367.appspot.com',
    iosClientId: '914139427259-78hnf2dh2pk5qtqinlkgj72laalco8oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICHC7DGkKOgaM__DVF_Jte3Hgvxgf4Pw',
    appId: '1:914139427259:ios:f55911251650280817149e',
    messagingSenderId: '914139427259',
    projectId: 'my-project-2024-7d367',
    storageBucket: 'my-project-2024-7d367.appspot.com',
    iosClientId: '914139427259-cnpsis3f7rild1jhmlblpqjr5fpk8pts.apps.googleusercontent.com',
    iosBundleId: 'com.example.fam.RunnerTests',
  );
}
